version: 2.1

orbs:
  python: circleci/python@0.2.1
  heroku: circleci/heroku@1.2.2

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python3 wsgi.py
workflows:
  heroku_deploy:
    jobs:
      #- build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: sequential-branch-filter
  main:
    jobs:
      - build-and-test
