version: 2.1

orbs:
  python: circleci/python@0.2.1
  heroku: circleci/heroku@1.2.2

jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          command: >
            echo "The command above installs Heroku, the command below deploys.
            What you do inbetween is up to you!"
      - heroku/deploy-via-git
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python3 hello.py
workflows:
  main:
    jobs:
      - deploy
      - build-and-test